/*
 * Copyright (c) 2018, Evgenii Zaitcev <zx_90@mail.ru>
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
*/

#include <stdio.h>
#include "ansi_color/ansi_color.h"

#define ANSI_COLOR_WORD "ANSI" ANSI_COLOR_RESET " "

#define ANSI_COLOR_LINE(STYLE, BACKGROUND) \
    printf("%-37s ", #BACKGROUND); \
    printf(STYLE BACKGROUND ANSI_COLOR_BLACK          ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_RED            ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_GREEN          ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_YELLOW         ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BLUE           ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_MAGENTA        ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_CYAN           ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_WHITE          ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_BLACK   ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_RED     ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_GREEN   ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_YELLOW  ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_BLUE    ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_MAGENTA ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_CYAN    ANSI_COLOR_WORD); \
    printf(STYLE BACKGROUND ANSI_COLOR_BRIGHT_WHITE   ANSI_COLOR_WORD); \
    printf("\n");

#define ANSI_COLOR_BLOCK(STYLE) \
    printf("STYLE: " #STYLE "\n\n"); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_NONE); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BLACK); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_RED); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_GREEN); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_YELLOW); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BLUE); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_MAGENTA); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_CYAN); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_WHITE); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_BLACK); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_RED); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_GREEN); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_YELLOW); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_BLUE); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_MAGENTA); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_CYAN); \
    ANSI_COLOR_LINE(STYLE, ANSI_COLOR_BACKGROUND_BRIGHT_WHITE); \
    printf("\n");

int main(void)
{
    printf("ANSI COLOR TEST.\n");
    printf("\n");
    ANSI_COLOR_BLOCK()
    ANSI_COLOR_BLOCK(ANSI_COLOR_BRIGHT)
    ANSI_COLOR_BLOCK(ANSI_COLOR_DIM)
    ANSI_COLOR_BLOCK(ANSI_COLOR_UNDERSCORE)
    ANSI_COLOR_BLOCK(ANSI_COLOR_BLINK)
    ANSI_COLOR_BLOCK(ANSI_COLOR_REVERSE)
    ANSI_COLOR_BLOCK(ANSI_COLOR_HIDDEN)
}

